services:
  db:
    image: docker.io/postgres:16.4-alpine3.20
    environment:
      POSTGRES_DB: roundest_phoenix_dev
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - roundest_phoenix_dev_data:/var/lib/postgresql/data
  site:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "0.0.0.0:4002:4000"
volumes:
  roundest_phoenix_dev_data:
