CREATE TABLE IF NOT EXISTS pokemon (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Name VARCHAR(255) NOT NULL,
    DexId INTEGER NOT NULL,
    UpVotes INTEGER DEFAULT 0,
    DownVotes INTEGER DEFAULT 0,
    InsertedAt TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create an index on dex_id since it's likely to be queried
CREATE INDEX IF NOT EXISTS idx_pokemon_dex_id ON pokemon(DexId);
